create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  user_id uuid references auth.users(id) on delete set null,
  account_email text,
  contact_email text,
  type text not null check (type in ('bug', 'feature')),
  status text not null default 'open' check (status in ('open', 'triaged', 'in_progress', 'resolved', 'closed')),
  title text not null check (char_length(title) between 4 and 160),
  description text not null check (char_length(description) between 10 and 5000),
  app_version text,
  platform text,
  reproduction_steps text,
  expected_behavior text,
  locale text not null default 'zh' check (locale in ('zh', 'en')),
  source text not null default 'web' check (source in ('web', 'app')),
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_user_id_idx on public.support_tickets(user_id);
create index if not exists support_tickets_status_created_idx on public.support_tickets(status, created_at desc);

alter table public.support_tickets enable row level security;

create policy "Users can read their own support tickets"
on public.support_tickets
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own support tickets"
on public.support_tickets
for insert
to authenticated
with check ((select auth.uid()) = user_id);

grant select, insert on public.support_tickets to authenticated;
grant select, insert, update, delete on public.support_tickets to service_role;
grant usage, select on sequence public.support_tickets_ticket_number_seq to authenticated, service_role;
